name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: run migrations and seed
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate:refresh --seed
    - name: compile vue components
      run: npm install && npm run dev
    - name: Git deploy to Heroku
      # You may pin to the exact commit or the version.
      # uses: onekiloparsec/heroku-node-deploy-subfolder@85d5701f800be8126e12b7f6f47e965c71f67b56
      uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
      with:
        # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
        api_key: 0c0ebac2-cfc6-486a-b322-f1302c851bc
        # The email of your Heroku account (needed for auth).
        email: tscandalitta@gmail.com
        # The app name to use for deploying/updating
        app_name: beermenu
        # The Heroku branch name that you would like to deploy to (`master` or `main`).
        heroku_branch: master
        # The subfolder where your built code is sitted, e.g. `dist`.
        subfolder: .
